name: Golang Linter
# Lint runs golangci-lint over the entire Pell Interactor repository.
#
# This workflow is run on every pull request and push to v0.38.x.
#
# The `golangci` job will pass without running if no *.{go, mod, sum}
# files have been modified.
#
# To run this locally, simply run `make lint` from the root of the repo.

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        name: Checkout Code

      - uses: actions/setup-go@v5
        name: Setup Go
        with:
          go-version: "1.23"
          cache: true

      - uses: golangci/golangci-lint-action@v6
        name: Run golangci-lint
        with:
          version: latest
          args: --timeout 10m
          github-token: ${{ secrets.GH_TOKEN }}
